/* Lấy danh sách nhân viên */
export const LAY_DS_NHAN_VIEN_DL = "LAY_DS_NHAN_VIEN_DL"
export const LAY_DS_NHAN_VIEN_DL_SUCCESS = "LAY_DS_NHAN_VIEN_DL_SUCCESS"
export const LAY_DS_NHAN_VIEN_DL_FAIL = "LAY_DS_NHAN_VIEN_DL_FAIL"

/* Xem chi tiết nhân viên*/
export const XEM_CTIET_NHAN_VIEN_DL = "XEM_CTIET_NHAN_VIEN_DL"
export const XEM_CTIET_NHAN_VIEN_DL_FAIL = "XEM_CTIET_NHAN_VIEN_DL_FAIL"
export const XEM_CTIET_NHAN_VIEN_DL_SUCCESS = "XEM_CTIET_NHAN_VIEN_DL_SUCCESS"

/**
 * Thêm nhân viên
 */
export const THEM_NHAN_VIEN_DL = "THEM_NHAN_VIEN_DL"
export const THEM_NHAN_VIEN_DL_MESAGE = "THEM_NHAN_VIEN_DL_MESAGE"
export const THEM_NHAN_VIEN_DL_FAIL = "THEM_NHAN_VIEN_DL_FAIL"
 
 /**
  * Chỉnh sửa nhân viên
  */
export const LAY_NHAN_VIEN_DL_CAP_NHAT= "LAY_NHAN_VIEN_DL_CAP_NHAT"
export const NHAN_VIEN_DL_CAP_NHAT= "NHAN_VIEN_DL_CAP_NHAT"
export const CHAP_NHAN_CAP_NHAT_NHAN_VIEN_DL = "CHAP_NHAN_CAP_NHAT_NHAN_VIEN_DL"
export const CAP_NHAT_NHAN_VIEN_DL_MESAGE = "CAP_NHAT_NHAN_VIEN_DL_MESAGE"
export const CAP_NHAT_NHAN_VIEN_DL_FAIL = "CAP_NHAT_NHAN_VIEN_DL_FAIL"
 
 /**
  * Delete user
  */
export const XOA_NHAN_VIEN_DL = "XOA_NHAN_VIEN_DL"
export const XOA_NHAN_VIEN_DL_MESAGE = "XOA_NHAN_VIEN_DL_MESAGE"
export const XOA_NHAN_VIEN_DL_FAIL = "XOA_NHAN_VIEN_DL_FAIL"
