const TaskActionTypes = {
  // lấy danh sách
  LAY_DS_LOAI_NHAN_VIEN : "LAY_DS_LOAI_NHAN_VIEN",
  LAY_DS_LOAI_NHAN_VIEN_SUCCESS : "LAY_DS_LOAI_NHAN_VIEN_SUCCESS",
  LAY_DS_LOAI_NHAN_VIEN_FAIL : "LAY_DS_LOAI_NHAN_VIEN_FAIL",
}

export default TaskActionTypes;