/* Lấy danh sách nhân viên */
export const LAY_DS_NHAN_VIEN = "LAY_DS_NHAN_VIEN"
export const LAY_DS_NHAN_VIEN_SUCCESS = "LAY_DS_NHAN_VIEN_SUCCESS"
export const LAY_DS_NHAN_VIEN_FAIL = "LAY_DS_NHAN_VIEN_FAIL"

/* Xem chi tiết nhân viên*/
export const XEM_CTIET_NHAN_VIEN = "XEM_CTIET_NHAN_VIEN"
export const XEM_CTIET_NHAN_VIEN_FAIL = "XEM_CTIET_NHAN_VIEN_FAIL"
export const XEM_CTIET_NHAN_VIENL_SUCCESS = "XEM_CTIET_NHAN_VIENL_SUCCESS"

/**
 * Thêm nhân viên
 */
export const THEM_NHAN_VIEN = "THEM_NHAN_VIEN"
export const THEM_NHAN_VIEN_MESAGE = "THEM_NHAN_VIEN_MESAGE"
export const THEM_NHAN_VIEN_FAIL = "THEM_NHAN_VIEN_FAIL"
 
 /**
  * Chỉnh sửa nhân viên
  */
export const LAY_NHAN_VIEN_CAP_NHAT= "LAY_NHAN_VIEN_CAP_NHAT"
export const NHAN_VIEN_CAP_NHAT= "NHAN_VIEN_CAP_NHAT"
export const CHAP_NHAN_CAP_NHAT_NHAN_VIEN = "CHAP_NHAN_CAP_NHAT_NHAN_VIEN"
export const CAP_NHAT_NHAN_VIEN_MESAGE = "CAP_NHAT_NHAN_VIEN_MESAGE"
export const CAP_NHAT_NHAN_VIEN_FAIL = "CAP_NHAT_NHAN_VIEN_FAIL"
 
 /**
  * Delete user
  */
export const XOA_NHAN_VIEN = "XOA_NHAN_VIEN"
export const XOA_NHAN_VIEN_MESAGE = "XOA_NHAN_VIEN_MESAGE"
export const XOA_NHAN_VIEN_FAIL = "XOA_NHAN_VIEN_FAIL"
